### ISSUE TITLE
Paragon Pack 1 not working in Sandbox mode

### ISSUE THREAD

**Issue by Rundas01** [jonesw66/BTD6-Mods#1]
if this issue has already been reported or this functionality is inteded, I'm sorry

**Comment by PixLNickz** [comment]
does it still work?

**Comment by Carogaph** [comment]
This is intended, normal paragons also don't work in sandbox. To test them, go into a normal game or give yourself a load of money in challenge editor.

**Comment by Rundas01** [comment]
my bad :3
